class UserSettings:
    INSTAFARM_MONGO_PASS: str
    INSTAFARM_MONGO_IP: str
    INSTAFARM_MONGO_USER: str
    INSTAFARM_MONGO_DB_NAME: str
    INSTAFARM_MONGO_PORT: str


SANIC_PORT = 8383
SANIC_HOST = "http://168.138.131.32"

FARM_FIELD_BASE_PRICE = 100
FARM_FIELD_PRICE_EXP = 5
USER_BASE_CAPITAL = 164.00

EXPOSE_ROUTERS = False
