name: Deploy code to server

on:
  workflow_call:
    inputs:
        server_ip:
          description: 'Server IP'
          type: string
    secrets:
      SSH_KEY:
        required: true
    
jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Start repository
        uses: actions/checkout@v2
        
      - name: Delete useless files
        run: |
          rm /home/runner/work/instafarm-async-api/instafarm-async-api/.gitignore
          rm /home/runner/work/instafarm-async-api/instafarm-async-api/README.md
          rm -rf /home/runner/work/instafarm-async-api/instafarm-async-api/.git/
          rm -rf /home/runner/work/instafarm-async-api/instafarm-async-api/.github/
          rm -rf /home/runner/work/instafarm-async-api/instafarm-async-api/.vscode/
        
      - name: Clean sanic folder
        continue-on-error: false
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ inputs.server_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/sanic/
      
      - name: Sync files for production
        uses: appleboy/scp-action@master
        with:
          host: ${{ inputs.server_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "/home/runner/work/instafarm-async-api/instafarm-async-api"
          target: "/home/ubuntu/sanic"

      - name: Install packages and restart service
        continue-on-error: false
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ inputs.server_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/sanic/
            sudo python3 -m venv venv/
            sudo venv/bin/python3 -m pip install -r requirements.txt
            sudo systemctl restart instafarm
